const answers = ["This is a sign. A bad sign.",
"Can you rephrase that?",
"There are is more than 1",
"Ask three more times",
"Blue",
"Purple",
"Red",
"What is your favorite color?",
"Toyota",
"BMW",
"Don't Blink.",
"I'm behind you",
"Just kidding xD",
"It's under your keyboard",
"Take a deep breath",
"Ask again later",
"Yes",
"No",
"In the fridge",
"I am hungry",
"Don't google that.",
"You're about to drop your phone",
"Omg are you serious?",
"Leave town.",
"CPP is better than JS",
"Watch out for bears",
"Bigfoot is real",
"That is not a good friend",
"That is a good friend",
"Send it",
"FUCKING SEND IT!!!",
"error"]